controller_configuration_credentials_secure_logging: false
controller_credentials:
  - name: student ssh password prompt_automated
    credential_type: Machine
    organization: Default
    inputs:
      username: student
      password: ASK
      become_password: ASK

